# Generated by Django 2.2.4 on 2021-03-23 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semi_rest_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='desc',
            field=models.TextField(null=True),
        ),
    ]
